### ISSUE TITLE
OpenWRT@ TP-Link WR-741ND V4 - Not cook image

### ISSUE THREAD

**Issue by Camis** [aparcar/attendedsysupgrade-server#101]
I'm waiting 12 hours, but image was not ready...

https://ledeupdate.planetexpress.cc/api/build-request/ce3f3b88187b
**queue: 1337**

https://ledeupdate.planetexpress.cc/api/build-request/bf89ae26b018
**queue: 1337**

OpenWRT@ TP-Link WR-741ND V4

Packages:

```
base-files
libc
libgcc
busybox
dropbear
mtd
uci
opkg
netifd
fstools
uclient-fetch
logd
kmod-gpio-button-hotplug
swconfig
kmod-ath9k
wpad-mini
uboot-envtools
dnsmasq
iptables
ip6tables
ppp
ppp-mod-pppoe
luci
```

**Comment by IBEBrasil** [comment]
I have the same problem with libremesh distribution on tp link 740 v6 model

**Comment by aparcar** [comment]
The worker seems down, I'll look into that. Sorry for the downtime!

**Comment by aparcar** [comment]
The server VM seem to have some trouble, I'm in contact with the admin and it's hopefully fixed soon

**Comment by IBEBrasil** [comment]
Great.thks....i am trying to create the fw with cooker for now.


Enviado do meu smartphone Samsung Galaxy.
-------- Mensagem original --------De: Paul Spooren <notifications@github.com> Data: 18/07/18  02:37  (GMT-03:00) Para: aparcar/attendedsysupgrade-server <attendedsysupgrade-server@noreply.github.com> Cc: IBEBrasil <instituto@bemestarbrasil.org.br>, Comment <comment@noreply.github.com> Assunto: Re: [aparcar/attendedsysupgrade-server] OpenWRT@ TP-Link WR-741ND V4 - Not cook image (#101) 
The server VM seem to have some trouble, I'm in contact with the admin and it's hopefully fixed soon

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/aparcar/attendedsysupgrade-server","title":"aparcar/attendedsysupgrade-server","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/aparcar/attendedsysupgrade-server"}},"updates":{"snippets":[{"icon":"PERSON","message":"@aparcar in #101: The server VM seem to have some trouble, I'm in contact with the admin and it's hopefully fixed soon"}],"action":{"name":"View Issue","url":"https://github.com/aparcar/attendedsysupgrade-server/issues/101#issuecomment-405814706"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/aparcar/attendedsysupgrade-server/issues/101#issuecomment-405814706",
"url": "https://github.com/aparcar/attendedsysupgrade-server/issues/101#issuecomment-405814706",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [aparcar/attendedsysupgrade-server] OpenWRT@ TP-Link WR-741ND V4 - Not cook image (#101)",
"sections": [
{
"text": "",
"activityTitle": "**Paul Spooren**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@aparcar",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"aparcar/attendedsysupgrade-server\",\n\"issueId\": 101,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"aparcar/attendedsysupgrade-server\",\n\"issueId\": 101\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/aparcar/attendedsysupgrade-server/issues/101#issuecomment-405814706"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 356563215\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by aparcar** [comment]
The previously requested image was now successfully build: 
https://chef.libremesh.org/#72b53f265d5a8ab
